apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pythonns-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rijmjada/helm-ayi/'        
    targetRevision: HEAD
    path: helm/python-chart                              
    helm:
      valueFiles:
        - values.yaml                                   
  destination:
    server: https://kubernetes.default.svc
    namespace: pythonns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
