apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace.name }}
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }} 