apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
  namespace: pythonns
spec:
  selector:
    app: simple-python-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort 