apiVersion: v2
name: python-chart
description: A Helm chart for FastAPI Python application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - python
  - kubernetes
  - web-application
home: https://github.com/rijmjada/k8sv2
sources:
  - https://github.com/rijmjada/k8sv2
maintainers:
  - name: Diego
    email: diego@example.com 