apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace.name }}
data:
  MYSQL_HOST: {{ .Values.fastapi.config.mysqlHost }}
  MYSQL_USER: {{ .Values.fastapi.config.mysqlUser }}
  MYSQL_DATABASE: {{ .Values.fastapi.config.mysqlDatabase }}
  MYSQL_PORT: {{ .Values.fastapi.config.mysqlPort | quote }}
  LOG_FILE: {{ .Values.fastapi.config.logFile }} 