apiVersion: v1
kind: Service
metadata:
  name: simple-python
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.fastapi.service.type }}
  selector:
    app: simple-python
  ports:
    - port: {{ .Values.fastapi.service.port }}
      targetPort: {{ .Values.fastapi.service.port }} 